import { Photo } from '../model'

export const photos: Photo[] = [
  { src: '148.jpg', author: 'MegabaitGamer', size: '3472-4640' },
  { src: '149.jpg', author: 'MegabaitGamer', size: '514-657' },
  { src: '150.png', author: 'MegabaitGamer', size: '1900-1994' },
  { src: '151.jpg', author: 'MegabaitGamer', size: '2772-2640' },
  { src: '152.jpg', author: 'MegabaitGamer', size: '800-666' },
  { src: '153.jpg', author: 'MegabaitGamer', size: '2560-1673' },
  { src: '154.png', author: 'MegabaitGamer', size: '2657-3209' },
  { src: '155.png', author: 'MegabaitGamer', size: '2700-1728' },
  { src: '156.png', author: 'MegabaitGamer' },
  { src: '157.png', author: 'MegabaitGamer' },
  { src: '158.png', author: 'MegabaitGamer' },
  { src: '159.jpg', author: 'MegabaitGamer' },
  { src: '160.jpg', author: 'MegabaitGamer' },
  { src: '161.jpg', author: 'MegabaitGamer' },
  { src: '162.jpg', author: 'MegabaitGamer' },
  { src: '163.jpg', author: 'MegabaitGamer' },
  { src: '164.jpg', author: 'MegabaitGamer' },
  { src: '1.png', author: 'Лилия Самохвалова' },
  { src: '2.png', author: 'Асеш Азария' },
  { src: '3.jpg', author: 'Sheryl' },
  { src: '4.jpg', author: 'Sheryl' },
  { src: '5.jpg', author: 'beemi' },
  { src: '6.png', author: 'Blue Лайм' },
  { src: '7.png', author: 'YuriS' },
  { src: '8.png', author: 'milkaFox' },
  { src: '9.png', author: 'milkaFox' },
  { src: '10.png', author: 'milkaFox' },
  { src: '11.png', author: 'milkaFox' },
  { src: '12.png', author: 'Александра Бондаренко' },
  { src: '13.png', author: 'shi_nda' },
  { src: '14.png', author: 'dev' },
  { src: '15.jpg', author: 'neddia_' },
  { src: '16.png', author: 'Villy' },
  { src: '17.png', author: 'Ртуть' },
  { src: '18.png', author: 'Shpilly Willy' },
  { src: '19.png', author: 'Уилл Зеленьский' },
  { src: '20.png', author: 'Анна Брак' },
  { src: '21.jpg', author: 'Косат(ик)' },
  { src: '22.png', author: 'Табуретка' },
  { src: '23.png', author: 'Дарья Шакурова' },
  { src: '24.png', author: 'BULKA' },
  { src: '25.jpg', author: 'Давента Амелис' },
  { src: '26.png', author: 'Royale High' },
  { src: '27.jpg', author: 'Grelka' },
  { src: '28.png', author: 'Yuki' },
  { src: '29.png', author: 'Елена Огнева' },
  { src: '30.png', author: 'Фраксус' },
  { src: '31.png', author: 'Spider' },
  { src: '32.jpg', author: 'Алина Кусь' },
  { src: '33.png', author: 'Арина Пловецкая' },
  { src: '34.png', author: 'Mitsura arts' },
  { src: '35.png', author: 'TOVAHKIIN' },
  { src: '36.jpg', author: 'Мария Вишнякова' },
  { src: '37.png', author: 'Диана Чечельницкая' },
  { src: '38.png', author: 'Екатерина Осипова' },
  { src: '39.png', author: 'Лисица' },
  { src: '40.png', author: 'Екатерина Усова' },
  { src: '41.jpg', author: 'dozhdoley' },
  { src: '42.jpg', author: 'dozhdoley' },
  { src: '43.jpg', author: 'dozhdoley' },
  { src: '44.jpg', author: 'dozhdoley' },
  { src: '45.jpg', author: 'dozhdoley' },
  { src: '46.png', author: 'dozhdoley' },
  { src: '47.jpg', author: 'dozhdoley' },
  { src: '48.jpg', author: 'dozhdoley' },
  { src: '49.jpg', author: 'dozhdoley' },
  { src: '50.jpg', author: 'dozhdoley' },
  { src: '51.jpg', author: 'dozhdoley' },
  { src: '52.jpg', author: 'dozhdoley' },
  { src: '53.png', author: 'Арина Шишкина' },
  { src: '54.png', author: 'Арина Шишкина' },
  { src: '55.jpg', author: 'untexp' },
  { src: '56.png', author: 'Леша Трахтенберг' },
  { src: '57.png', author: 'Леша Трахтенберг' },
  { src: '58.png', author: 'AirFly-pony' },
  { src: '59.png', author: 'SonyaGer' },
  { src: '60.png', author: 'Паша Евтеров' },
  { src: '61.png', author: 'Аня Чистякова' },
  { src: '62.jpg', author: 'Алена Миронова' },
  { src: '63.png', author: 'Horned Unicorn' },
  { src: '64.jpg', author: 'Reys The-Human' },
  { src: '65.png', author: 'maslo' },
  { src: '66.png', author: 'Эльмира Мастеренко' },
  { src: '67.jpg', author: 'Роман Брабус' },
  { src: '68.jpg', author: 'DOROTEA' },
  { src: '69.jpg', author: 'Ева Сахаркова' },
  { src: '70.png', author: 'Qwokken Sporghkjlp' },
  { src: '71.png', author: 'Полина Астафурова' },
  { src: '72.png', author: 'MWerryCult' },
  { src: '73.jpg', author: 'Лима Скрайт' },
  { src: '74.png', author: 'Cake Bats' },
  { src: '75.png', author: 'ТУЧЕЛЬ' },
  { src: '76.png', author: 'Ксения Бисько' },
  { src: '77.png', author: 'Стас Придурок' },
  { src: '78.png', author: 'mithriss' },
  { src: '79.jpg', author: 'DARSON FAMILY' },
  { src: '80.png', author: 'Hypocritical elf ' },
  { src: '81.png', author: 'Arian Raif' },
  { src: '82.png', author: 'Станислав Бойко' },
  { src: '83.jpg', author: 'Xe-N-do~iLL 69' },
  { src: '84.png', author: 'Аня Виноградова' },
  { src: '85.png', author: 'Аня Виноградова' },
  { src: '86.jpg', author: '' },
  { src: '87.jpg', author: 'AstroNaut_F' },
  { src: '88.png', author: 'BuvanyBu' },
  { src: '89.jpg', author: 'Deo Marzipan' },
  { src: '90.png', author: 'Мария Черепашкина' },
  { src: '91.png', author: 'Диана Ибрагимова' },
  { src: '92.png', author: 'OLGA BOD' },
  { src: '93.png', author: 'Маха Хоронжук' },
  { src: '94.jpg', author: 'Dann' },
  { src: '95.jpg', author: 'Юлия Славкина' },
  { src: '96.png', author: 'Вероника Крыскина' },
  { src: '97.png', author: 'Ваня Чабрец' },
  { src: '98.png', author: 'Тори' },
  { src: '99.png', author: 'Вероника Птичка' },
  { src: '100.png', author: 'Rubin O.B.' },
  { src: '101.png', author: 'Люба Маркова' },
  { src: '102.jpg', author: 'Маргарита Минькова' },
  { src: '103.jpg', author: 'Татьяна Лисовиц' },
  { src: '104.png', author: 'Персик' },
  { src: '105.png', author: 'Oleg Gogol' },
  { src: '106.png', author: 'copyofastrid' },
  { src: '107.png', author: 'Юлия Химиченко' },
  { src: '108.png', author: 'Полина Печкина' },
  { src: '109.png', author: 'Im Not' },
  { src: '110.png', author: 'SherCore' },
  { src: '111.jpg', author: 'Паша Цезарь' },
  { src: '112.png', author: 'Нина Вишнёвская' },
  { src: '113.png', author: 'Нина Вишнёвская' },
  { src: '114.png', author: 'Нина Вишнёвская' },
  { src: '115.jpg', author: 'BurntSyrop' },
  { src: '116.png', author: 'Christopher Ray' },
  { src: '117.jpg', author: 'OREX' },
  { src: '118.png', author: 'Remember the past and create the future' },
  { src: '119.png', author: 'Ирина Гарькавец' },
  { src: '120.jpg', author: 'шпротина' },
  { src: '121.png', author: 'Ольга Коржичкина' },
  { src: '122.png', author: 'Tweek' },
  { src: '123.jpg', author: 'Александра Кострова' },
  { src: '124.jpg', author: 'Ghosha' },
  { src: '125.jpg', author: 'Юлия Гнездилова' },
  { src: '126.jpg', author: 'DjkaSkan' },
  { src: '127.png', author: 'Татьяна Богомол' },
  { src: '128.png', author: 'h1kkage' },
  { src: '129.jpg', author: 'xeniyy' },
  { src: '130.png', author: 'coal_pit' },
  { src: '131.jpg', author: 'Лена Заровная' },
  { src: '132.png', author: 'Алина Ковалёва' },
  { src: '133.png', author: 'Алина Ковалёва' },
  { src: '134.jpg', author: 'Devi' },
  { src: '135.jpg', author: 'Devi' },
  { src: '136.jpg', author: 'Devi' },
  { src: '137.jpg', author: 'Devi' },
  { src: '138.jpg', author: 'Devi' },
  { src: '139.jpg', author: 'Devi' },
  { src: '140.jpg', author: 'Devi' },
  { src: '141.jpg', author: 'Devi' },
  { src: '142.jpg', author: 'Devi' },
  { src: '143.jpg', author: 'Devi' },
  { src: '144.jpg', author: 'Devi' },
  { src: '145.jpg', author: 'Devi' },
  { src: '146.png', author: 'Нает' },
  { src: '147.jpg', author: 'dozhdoley' },
  { src: '165.jpg', author: 'MegabaitGamer' },
  { src: '166.png', author: 'MegabaitGamer' }
]
